[creativeModeTabs]
	enableCreativeModeTabs = true
	syncSelectedCreativeModeTab = true

[stackGroups]
	enableStackGroups = true
	disabledStackGroups = ["mekanism:unit", "mekanism:crystals", "mekanism:dirty_dusts", "mekanism:enriched", "mekanism:clumps", "mekanism:shards", "minecraft:stairs", "minecraft:slabs", "minecraft:walls", "minecraft:trapdoors", "minecraft:doors", "c:raw_materials"]
